apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "claudia.fullname" . }}-data
  labels:
    {{- include "claudia.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.pvc.size | quote }}
  {{- with .Values.pvc.storageClassName }}
  storageClassName: {{ . | quote }}
  {{- end }}
